---
production:
  hosts: {}

staging:
  hosts: {}

test:
  hosts: {}

bootstrap:
  hosts:
    bhft_test_vm:
      ansible_host: x.x.x.x

all:
  children:
    production:
    staging:
    test:
    bootstrap:
